apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/components: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/components: server
  ports:
    - port: 25565
      targetPort: server
      protocol: TCP
      name: server