apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/components: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft
      app.kubernetes.io/components: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft
        app.kubernetes.io/components: server
    spec:
      containers:
      - name: minecraft
        image: marshmeg/minecraft-server:1.21-vanila
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 25565
          name: server
        volumeMounts:
          - mountPath: /minecraft
            name: my-volume
      volumes:
      - name: my-volume
        hostPath:
          path: C:/server/minecraft1.21/src/
          type: ""
